message(STATUS "Configuring Linux native build")
include_directories(${KRIT_DIR}/toolchain/linux/include/freetype2)
include_directories(BEFORE ${KRIT_DIR}/toolchain/linux/include)
set(TOOLCHAIN_LIB_PATH ${KRIT_DIR}/toolchain/linux/lib)
set(CMAKE_C_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -ldl")
set(KRIT_USE_GLEW OFF)
include("${CMAKE_SOURCE_DIR}/krit/toolchain/desktop.cmake")
