message(STATUS "Configuring Windows build")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static -static-libgcc -static-libstdc++ -lwinpthread")
set(KRIT_PLATFORM_STATIC_LIBS "-lmingw32 -mwindows -Wl,--dynamicbase -Wl,--nxcompat -lm -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lsetupapi -lversion -luuid -lws2_32 -lcrypt32 -lavrt -lbcrypt -fno-stack-protector -ldbghelp")
set(CMAKE_FIND_LIBRARY_PREFIXES "lib" "")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".dll.a" ".lib" ".a")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -mconsole")
set(KRIT_STATIC "-Wl,-Bstatic")
set(TOOLCHAIN_LIB_PATH ${KRIT_DIR}/toolchain/windows/lib)
include_directories(SYSTEM ${CMAKE_SOURCE_DIR}/krit/toolchain/windows/include)
include_directories(SYSTEM ${CMAKE_SOURCE_DIR}/krit/toolchain/windows/include/freetype2)
link_directories(${CMAKE_SOURCE_DIR}/krit/toolchain/windows/bin)
include("${CMAKE_SOURCE_DIR}/krit/toolchain/desktop.cmake")
add_definitions(-DZIP_STATIC)
