set(KRIT_BACKEND_NET Curl CACHE STRING "Net backend")
set(KRIT_BACKEND_IO Zip CACHE STRING "IO backend")
set(KRIT_BACKEND_PLATFORM Desktop CACHE STRING "Platform backend")
set(KRIT_BACKEND_RENDERER Gl CACHE STRING "Renderer backend")

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")

add_definitions(-DKRIT_DESKTOP)
add_definitions(-DKRIT_SOUND_THREAD)
include_directories(${KRIT_DIR}/argparse/include)
include_directories(${KRIT_DIR}/tinyfiledialogs)
list(APPEND KRIT_SRC_FILES ${KRIT_DIR}/tinyfiledialogs/tinyfiledialogs.c)

# dynamic libs
find_package(OpenGL REQUIRED)

# static libs
find_library(JPEG_LIB NAMES libjpeg.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(PNG_LIB NAMES libpng.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(SDL_IMAGE_LIB NAMES libSDL2_image.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(SDL_LIB NAMES libSDL2.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
# find_library(SDL_MAIN_LIB NAMES libSDL2main.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(CURL_LIB NAMES libcurl.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
add_definitions(-DCURL_STATICLIB)
find_library(CRYPTO_LIB NAMES libcrypto.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(SSL_LIB NAMES libssl.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(FLAC_LIB NAMES libFLAC.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(FREETYPE_LIB NAMES libfreetype.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(HARFBUZZ_LIB NAMES libharfbuzz.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(OGG_LIB NAMES libogg.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(OPUS_LIB NAMES libopus.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(SNDFILE_LIB NAMES libsndfile.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(SQLITE3_LIB NAMES libsqlite3.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(VORBIS_LIB NAMES libvorbis.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(VORBISENC_LIB NAMES libvorbisenc.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(YAML_LIB NAMES libyaml.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(Z_LIB NAMES libz.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(ZIP_LIB NAMES libzip.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(OPENAL_LIB NAMES libopenal.a libOpenAL32.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
add_definitions(-DAL_LIBTYPE_STATIC -DAL_ALEXT_PROTOTYPES)
list(APPEND KRIT_LIBS
    ${OPENGL_LIBRARIES}
)
list(APPEND KRIT_STATIC_LIBS
    ${OPENAL_LIB}
    ${SDL_LIB}
    # ${SDL_MAIN_LIB}
    ${SDL_IMAGE_LIB}
    ${JPEG_LIB}
    ${PNG_LIB}
    ${CURL_LIB}
    ${SQLITE3_LIB}
    ${HARFBUZZ_LIB}
    ${FREETYPE_LIB}
    ${HARFBUZZ_LIB}
    ${SNDFILE_LIB}
    ${VORBIS_LIB}
    ${VORBISENC_LIB}
    ${FLAC_LIB}
    ${OPUS_LIB}
    ${OGG_LIB}
    ${YAML_LIB}
    ${ZIP_LIB}
    ${SSL_LIB}
    ${CRYPTO_LIB}
    ${Z_LIB}
)
