set(KRIT_BACKEND_PLATFORM Desktop CACHE STRING "Platform backend")
set(KRIT_BACKEND_RENDERER Gl CACHE STRING "Renderer backend")

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")

option(KRIT_ENABLE_DIALOGS "Enable system file dialogs" ON)
if(KRIT_ENABLE_DIALOGS)
    add_compile_definitions(krit INTERFACE -DKRIT_ENABLE_DIALOGS)
    include_directories(${CMAKE_CURRENT_LIST_DIR}/../tinyfiledialogs)
    list(APPEND KRIT_SRC_FILES ${CMAKE_CURRENT_LIST_DIR}/../tinyfiledialogs/tinyfiledialogs.c)
endif()

add_definitions(-DKRIT_DESKTOP)
if(KRIT_ENABLE_THREADS)
    add_compile_definitions(krit INTERFACE -DKRIT_SOUND_THREAD)
endif()
target_include_directories(krit INTERFACE ${CMAKE_CURRENT_LIST_DIR}/../argparse/include)

# dynamic libs
find_package(OpenGL REQUIRED)
list(APPEND KRIT_LIBS
    ${OPENGL_LIBRARIES}
)

message(STATUS "TOOLCHAIN LIB PATH: ${TOOLCHAIN_LIB_PATH}")

# static libs
find_library(JPEG_LIB NAMES libjpeg.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(PNG_LIB NAMES libpng.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(SDL_IMAGE_LIB NAMES libSDL3_image.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(SDL_LIB NAMES libSDL3.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(YAML_LIB NAMES libyaml.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(Z_LIB NAMES libz.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
find_library(ZIP_LIB NAMES libzip.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)

list(APPEND KRIT_STATIC_LIBS
    ${SDL_LIB}
    ${SDL_IMAGE_LIB}
    ${JPEG_LIB}
    ${PNG_LIB}
    ${YAML_LIB}
    ${ZIP_LIB}
    ${Z_LIB}
)

if(KRIT_ENABLE_NET)
    set(KRIT_BACKEND_NET Curl CACHE STRING "Net backend")
    find_library(CURL_LIB NAMES libcurl.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
    add_definitions(-DCURL_STATICLIB)
    find_library(CRYPTO_LIB NAMES libcrypto.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
    find_library(SSL_LIB NAMES libssl.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
    list(APPEND KRIT_STATIC_LIBS
        ${CURL_LIB}
        ${SSL_LIB}
        ${CRYPTO_LIB}
    )
endif()
if(KRIT_ENABLE_TEXT)
    find_library(FREETYPE_LIB NAMES libfreetype.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
    find_library(HARFBUZZ_LIB NAMES libharfbuzz.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
    list(APPEND KRIT_STATIC_LIBS
        ${HARFBUZZ_LIB}
        ${FREETYPE_LIB}
    )
endif()
if(KRIT_ENABLE_AUDIO)
    find_library(FLAC_LIB NAMES libFLAC.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
    find_library(OGG_LIB NAMES libogg.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
    find_library(OPUS_LIB NAMES libopus.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
    find_library(VORBIS_LIB NAMES libvorbis.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
    find_library(VORBISENC_LIB NAMES libvorbisenc.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
    find_library(SNDFILE_LIB NAMES libsndfile.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
    find_library(OPENAL_LIB NAMES libopenal.a libOpenAL32.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
    add_definitions(-DAL_LIBTYPE_STATIC -DAL_ALEXT_PROTOTYPES)
    list(APPEND KRIT_STATIC_LIBS
        ${OPENAL_LIB}
        ${SNDFILE_LIB}
        ${VORBIS_LIB}
        ${VORBISENC_LIB}
        ${FLAC_LIB}
        ${OPUS_LIB}
        ${OGG_LIB}
    )
endif()
if(KRIT_ENABLE_SQLITE)
    find_library(SQLITE3_LIB NAMES libsqlite3.a HINTS "${TOOLCHAIN_LIB_PATH}" REQUIRED CMAKE_FIND_ROOT_PATH_BOTH)
    list(APPEND KRIT_STATIC_LIBS
        ${SQLITE3_LIB}
    )
endif()
