message(STATUS "Configuring Emscripten build")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-c99-designator -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s USE_FREETYPE=1 -s USE_HARFBUZZ=1 -s USE_ZLIB=1")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -gsource-map")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --bind -s USE_SDL=2 -s USE_SDL_IMAGE=2 --use-preload-plugins --preload-file assets -s INITIAL_MEMORY=536870912 -s MAX_WEBGL_VERSION=2 -s MIN_WEBGL_VERSION=2 -s ALLOW_MEMORY_GROWTH=1 -s USE_LIBPNG=1")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG} -gsource-map --source-map-base http://localhost:8000/ -s ASSERTIONS=1")
# link_directories(${CMAKE_CURRENT_SOURCE_DIR}/toolchain/emscripten/lib)
include_directories(BEFORE ${KRIT_DIR}/toolchain/emscripten/include)
set(TOOLCHAIN_LIB_PATH ${KRIT_DIR}/toolchain/emscripten/lib)
set(CMAKE_FIND_LIBRARY_PREFIXES "lib" "")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".so" ".a")
set(KRIT_ENABLE_THREADS OFF)
set(KRIT_ENABLE_TOOLS OFF)
set(KRIT_USE_GLEW OFF)
set(KRIT_ENABLE_MULTISAMPLING OFF)
set(CMAKE_EXECUTABLE_SUFFIX ".html")
