message(STATUS "Configuring Linux native build")
target_include_directories(krit INTERFACE ${CMAKE_CURRENT_LIST_DIR}/linux/include/freetype2)
target_include_directories(krit BEFORE INTERFACE ${CMAKE_CURRENT_LIST_DIR}/linux/include)
set(AUTOTOOLS_HOST_TRIPLET "x86_64-pc-linux-gnu")
set(SDL_CMAKE_ARGS "-DSDL_X11=ON;-DSDL_X11_SHARED=ON")
set(CMAKE_C_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -ldl")
set(KRIT_USE_GLEW On)
include("${CMAKE_CURRENT_LIST_DIR}/desktop.cmake")
